### ISSUE TITLE
Why is there `version(none):` at the beginning of bcrypt?

### ISSUE THREAD

**Issue by tmccombs** [etcimon/botan#18]
Commit 8e5563347da4af4ceae002c29d6e78463392e558 by @etcimon added `version(none):` at the beginning of the bcrypt.d file. This doesn't seem to be related to the commit message "update ciphersuite for chacha20".  

Was this change intentional? If so why was it put in, is the bcrypt implementation not functional?

**Comment by etcimon** [comment]
This was a workaround for an ICE on a specific project, no way to pinpoint it really but for most it shouldn't be an issue. I simply forgot to re-enable bcrypt before pushing
