### ISSUE TITLE
broken dmd release build

### ISSUE THREAD

**Issue by MartinNowak** [etcimon/botan#23]
Always end up in `botan.tls.extensions.SupportedEllipticCurves.nameToCurveId` w/ no arguments and a broken stack trace. I'd guess because of some memory corruption.

```
#0  botan.tls.extensions.SupportedEllipticCurves.nameToCurveId(const(immutable(char)[])) (name=...)
    at ../../../../.dub/packages/botan-1.12.7/botan/source/botan/tls/extensions.d:791
#1  0x0000000000000000 in ?? ()
```

**Comment by etcimon** [comment]
Any details regarding the other dependencies or usage?

**Comment by etcimon** [comment]
Also, build "versions" tags, did you try `DisableDebugger` or `EnableDebugger`? Is this a core dump or a gdb debugging session / reproducible?

**Comment by etcimon** [comment]
Do you use concurrency? Which curves are you using?

**Comment by etcimon** [comment]
Try removing the name append here: https://github.com/etcimon/botan/blob/v1.12.7/source/botan/tls/extensions.d#L790 which could have been deserialized as null maybe?

**Comment by MartinNowak** [comment]
The stack trace is fairly broken, so it might not even be a regular call.

**Comment by etcimon** [comment]
Did you provide a custom curve list? Which DMD version does this run with?

**Comment by MartinNowak** [comment]
No, I did not, seems like `policy.allowedEccCurves()` get's broken.
```d
import std.stdio;
auto curves = policy.allowedEccCurves();
foreach (c; curves)
    writeln("allowedEccCurves: ", c);
```
It's dmd 2.071.2.

**Comment by etcimon** [comment]
Ok with that info I'll attempt to update my DMD version tomorrow and reproduce

**Comment by MartinNowak** [comment]
> Ok with that info I'll attempt to update my DMD version tomorrow and reproduce

I can recommend `curl -fsS https://dlang.org/install.sh | bash -s dmd-2.071.2` ;).

**Comment by etcimon** [comment]
I decided to test run everything with 2.072.0, lots of regressions and errors. I couldn't get the same error but I can downgrade to 2.071.2 to see

**Comment by MartinNowak** [comment]
Seems like the error happens in vibe.d filling it's CustomTLSPolicy, can take care of the rest of debugging.

**Comment by MartinNowak** [comment]
Duplicate of https://github.com/rejectedsoftware/vibe.d/issues/1578
