### ISSUE TITLE
Build failing with DMD 2.072.0

### ISSUE THREAD

**Issue by LightBender** [etcimon/botan#24]
Build is failing with the following error:

../../.dub/packages/botan-1.12.7/botan/source/botan/utils/http_util/http_util.d(29,12): Error: module stream is in file 'std/stream.d' which cannot be read

This appears related to the removal std.stream in 2.072.0

Tried running dub upgrade. No change.

**Comment by etcimon** [comment]
Should be good with master, I'll create a new tag

**Comment by etcimon** [comment]
Try v1.12.8 see if that works

**Comment by LightBender** [comment]
That fixed it, thank you!
