### ISSUE TITLE
SegFault while encoding PEM+BER for Public/Private ECC Keys

### ISSUE THREAD

**Issue by LightBender** [etcimon/botan#25]
Given:

	auto rng = new AutoSeededRNG();
	auto ecg = ECGroup("secp384r1");
	auto key = ECDHPrivateKey(rng, ecg);
	auto privKey = key.m_priv;
	auto pubKey = cast(ECPublicKey)key.m_priv;

This will fail for public keys:

	import botan.pubkey.x509_key : PEM_encode;
	import botan.pubkey.x509_key : BER_encode;
	auto ber = BER_encode(pubKey);
	auto pem = PEM_encode(pubKey);
	return pem;

This will fail for private keys without password:

	import botan.pubkey.pkcs8 : PEM_encode;
	return PEM_encode(privKey);

Same for with password. Any time I try to encode to PEM or BER I am greeted with a SegFault.

This is with the latest LDC. The DMD build is broken on OSX

**Comment by etcimon** [comment]
Do you have a gdb backtrace by any chance?

**Comment by LightBender** [comment]
I don't, but the above snippets are sufficient to reproduce the error.
