### ISSUE TITLE
Error compiling on Ubuntu 14.04, x86

### ISSUE THREAD

**Issue by aberba** [etcimon/botan#26]
I get warning:
```sh
Running pre-generate commands for botan:base...
Notice: Botan uses many symbols. Look into switching from ld (bfd) to ld (Gold) linker to reduce link times from >15s to <2s
Performing "debug" build using dmd for x86.
botan-math 1.0.3: target for configuration "regular" is up to date.
```

and finally exit with error:

```sh
Enhanced memory security is enabled.
Memory debugger enabled
../../../../.dub/packages/vibe-d-0.7.30/vibe-d/source/vibe/stream/botan.d(775,16): Error: undefined identifier 'BigInt'
dmd failed with exit code 1.
```

**Comment by etcimon** [comment]
Hello

Could you try adding `import botan.math.bigint.bigint: BigInt;` at the top of the file at `../../../../.dub/packages/vibe-d-0.7.30/vibe-d/source/vibe/stream/botan.d` ?

**Comment by aberba** [comment]
It worked!! 

Was it a problem with vibe.d?

**Comment by KrzaQ** [comment]
Will this be fixed  in vibe 0.7? I'm still getting it on arch linux.

**Comment by aberba** [comment]
I later found out botan was not well tested on x86. Some algorithms assumed x64 architecture. Bcrypt password in particular

**Comment by KrzaQ** [comment]
I'm getting it on x86_64, so this probably isn't it.

```
>  uname -a
Linux ArchVM 4.9.11-1-ARCH #1 SMP PREEMPT Sun Feb 19 13:45:52 UTC 2017 x86_64 GNU/Linux
```
