### ISSUE TITLE
How to use blowfish?

### ISSUE THREAD

**Issue by Abscissa** [etcimon/botan#28]
I've been trying to go through the docs, but I'm still at a complete loss: If I want to create blowfish hashes, paramaterized by complexity (as is a large part of the point of blowfish, vs say SHA2), then...how do I do that in botan?

**Comment by etcimon** [comment]
You should look at how [cryptobox](https://github.com/etcimon/botan/blob/master/source/botan/constructs/cryptobox.d#L59) is implemented. For blowfish you would replace Serpent with Blowfish. So basically, you'd be using the `getCipher` function from `botan.libstate.lookup` and manipulate it as a `KeyedFilter`/`Filterable` object through a `Pipe`.

**Comment by etcimon** [comment]
Although, I think you're talking about [passhash](https://github.com/etcimon/botan/blob/master/source/botan/passhash/bcrypt.d)?

**Comment by Abscissa** [comment]
Yes, I was indeed. Thanks.
