### ISSUE TITLE
DUB failing using ldc

### ISSUE THREAD

**Issue by Mariomm-marti** [etcimon/botan#42]
**Compiler:** ldc
**OS Architecture:** x86_64
**Linux distribution:** 4.15.6-1-ARCH
**Dub.sdl:**
```
dependency "vibe-d" version="~>0.8.3-beta.1"
dependency "vibe-d:tls" version="~>0.8.3-beta.1"
versions "VibeDefaultMain"
subConfiguration "vibe-d:tls" "botan"
```
**Error log:** https://hastebin.com/wubujowezi.coffeescript
**When did start to happen:** Yesterday I updated my DUB package to version 1.8.0

**Comment by denizzzka** [comment]
> Error log: https://hastebin.com/wubujowezi.coffeescript

Invalid link
