### ISSUE TITLE
import botan.* causes crash DMD

### ISSUE THREAD

**Issue by denizzzka** [etcimon/botan#45]
```D
/+ dub.json:
{
  "name": "crypto",
  "targetType_": "library",
  "dependencies": {
    "botan": "~>1.12.9"
  }
}
+/

void main()
{
  // Enabling any of this imports causes DMD fail:
  import botan.passhash.bcrypt;
  import botan.rng.rng;
  import botan.rng.auto_rng;
}
```

```
$ dub run --single crypto.d
Running pre-generate commands for botan...
Notice: Botan uses many symbols. Look into switching from ld (bfd) to ld (Gold) linker to reduce link times from >15s to <2s
Performing "debug" build using /usr/bin/dmd for x86_64.
botan-math 1.0.3: target for configuration "regular" is up to date.
memutils 0.4.10: target for configuration "secure" is up to date.
botan 1.12.9: target for configuration "full" is up to date.
crypto ~master: building configuration "application"...
/home/denizzz/.dub/packages/memutils-0.4.10/memutils/source/memutils/refcounted.d(54,2): Deprecation: const postblit is deprecated. Please use an unqualified postblit.
Enhanced memory security is enabled.
Memory debugger enabled
Segmentation fault (core dumped)
/usr/bin/dmd failed with exit code 139.
```

Tested on DMD 2.079 and 2.080

**Comment by denizzzka** [comment]
Example `botan/examples/bcrypt/source/bcrypt.d` also affected

**Comment by denizzzka** [comment]
https://forum.dlang.org/post/repayocxhsojtijynqhe@forum.dlang.org

**Comment by etcimon** [comment]
I think this might be an issue with a newer version of DMD, I still use 2.075.1 at the moment.

**Comment by triplejam** [comment]
It seems to have to do with some change between versions 2.077 and 2.078.3. I think it is also happening now with the latest ldc release 1.9 because it was giving a similar error message, which led me to this thread.

If I add  -v to dflags it looks like dmd chokes at a certain point
`...

function  std.algorithm.mutation.moveEmplace!(ushort[]).moveEmplace
function  memutils.vector.Vector!(void delegate(), ThreadMem).Vector.__xopEquals
/usr/bin/dmd failed with exit code -11.`

And there are some changes in algorithm.mutation in between those two versions. Maybe that could be part of the issue?

**Comment by triplejam** [comment]
@denizzzka I debugged it a bit to find the spot and opened an issue:
https://issues.dlang.org/show_bug.cgi?id=19000

**Comment by etcimon** [comment]
That's great, thanks for the help. I've often had these kind of crashes with dmd, the way to debug is it to build a debug version of dmd and use windbg or gdb 
(linux) to look at locals and see how it misbehaves. I'll do this when I get the chance, for now I'm in a stable environment so I hadn't had the need to upgrade yet.

**Comment by dariusc93** [comment]
Good to know there is a an issue with botan and the latest version of dmd. I did recently upgrade dmd (the latest did improve alot of things and fixed some bugs) and was about to rebuild something that I use botan for but decided to check here to see if there is any bugs or issues that I should be aware of.
