### ISSUE TITLE
found 'pure' when expecting '{'

### ISSUE THREAD

**Issue by Shananra** [etcimon/botan#5]
Attempting to compile my project using dub, and I am getting the following compile errors. I tried creating a new project as well to see if there was a conflict, the error below was from this new project with nothing  but botan in the dependencies and no other code written:

Running pre-generate commands for botan...
Notice: Botan uses many symbols. Look into switching from ld (bfd) to ld (Gold) linker to reduce link times from >15s to <2s
Building memutils 0.4.1 configuration "secure", build type debug.
Running dmd...
Enhanced memory security is enabled.
Building botan 1.12.0 configuration "full", build type debug.
Running dmd...
../../../../../../shananra/.dub/packages/botan-1.12.0/source/botan/math/mp/mp_core.d(1769): Error: found 'pure' when expecting '{'
../../../../../../shananra/.dub/packages/botan-1.12.0/source/botan/math/mp/mp_core.d(1771): Error: mismatched number of curly brackets
../../../../../../shananra/.dub/packages/botan-1.12.0/source/botan/math/mp/mp_core.d(1772): Error: mismatched number of curly brackets
../../../../../../shananra/.dub/packages/botan-1.12.0/source/botan/math/mp/mp_core.d(1773): Error: mismatched number of curly brackets
../../../../../../shananra/.dub/packages/botan-1.12.0/source/botan/math/mp/mp_core.d(1774): Error: mismatched number of curly brackets
../../../../../../shananra/.dub/packages/botan-1.12.0/source/botan/math/mp/mp_core.d(1775): Error: mismatched number of curly brackets
../../../../../../shananra/.dub/packages/botan-1.12.0/source/botan/math/mp/mp_core.d(1776): Error: mismatched number of curly brackets
../../../../../../shananra/.dub/packages/botan-1.12.0/source/botan/math/mp/mp_core.d(1777): Error: mismatched number of curly brackets
../../../../../../shananra/.dub/packages/botan-1.12.0/source/botan/math/mp/mp_core.d(1778): Error: mismatched number of curly brackets
../../../../../../shananra/.dub/packages/botan-1.12.0/source/botan/math/mp/mp_core.d(1779): Error: mismatched number of curly brackets
../../../../../../shananra/.dub/packages/botan-1.12.0/source/botan/math/mp/mp_core.d(1780): Error: mismatched number of curly brackets
../../../../../../shananra/.dub/packages/botan-1.12.0/source/botan/math/mp/mp_core.d(1784): Error: found 'else' instead of statement
../../../../../../shananra/.dub/packages/botan-1.12.0/source/botan/math/mp/mp_core.d(1812): Error: found 'pure' when expecting '{'
../../../../../../shananra/.dub/packages/botan-1.12.0/source/botan/math/mp/mp_core.d(1813): Error: mismatched number of curly brackets
../../../../../../shananra/.dub/packages/botan-1.12.0/source/botan/math/mp/mp_core.d(1814): Error: mismatched number of curly brackets
../../../../../../shananra/.dub/packages/botan-1.12.0/source/botan/math/mp/mp_core.d(1815): Error: mismatched number of curly brackets
../../../../../../shananra/.dub/packages/botan-1.12.0/source/botan/math/mp/mp_core.d(1816): Error: mismatched number of curly brackets
../../../../../../shananra/.dub/packages/botan-1.12.0/source/botan/math/mp/mp_core.d(1817): Error: mismatched number of curly brackets
../../../../../../shananra/.dub/packages/botan-1.12.0/source/botan/math/mp/mp_core.d(1818): Error: mismatched number of curly brackets
../../../../../../shananra/.dub/packages/botan-1.12.0/source/botan/math/mp/mp_core.d(1819): Error: mismatched number of curly brackets
../../../../../../shananra/.dub/packages/botan-1.12.0/source/botan/math/mp/mp_core.d(1820): Error: mismatched number of curly brackets
FAIL ../../../../../../shananra/.dub/packages/botan-1.12.0/.dub/build/full-debug-linux.posix-x86_64-dmd_2066-EBCDE32E6948503DC31BAE384BD48A40/ botan staticLibrary
Error executing command run: dmd failed with exit code 1.

The above was an attempt to build with "dub test --arch=x86_64"

**Comment by etcimon** [comment]
> FAIL ../../../../../../shananra/.dub/packages/botan-1.12.0/.dub/build/full-debug-linux.posix-x86_64-dmd_2066-EBCDE32E6948503DC31BAE384BD48A40/ botan staticLibrary

This is due to the incompatibility with DMD 2.066. Botan assembly is marked pure, which was added in DMD 2.067.0. If you upgrade your installation of DMD, it should work just fine

**Comment by Shananra** [comment]
That was it. Thanks!
