### ISSUE TITLE
undefined identifier pbes2Encrypt

### ISSUE THREAD

**Issue by apanys** [etcimon/botan#56]
While specifying configuration `pubkey` syntax errors are thrown:
``` json
{
	"dependencies": {
		"botan": "1.12.18"
	},
    "subConfigurations": {
        "botan": "pubkey"
    },
	"name": "t3"
}
```

..\..\AppData\Local\dub\packages\botan-1.12.18\botan\source\botan\pubkey\pkcs8.d(101,3): Error: undefined identifier pbes2Encrypt
..\..\AppData\Local\dub\packages\botan-1.12.18\botan\source\botan\pubkey\pkcs8.d(295,11): Error: undefined identifier pbes2Decrypt

**Comment by etcimon** [comment]
The pubkey example now uses this configuration and it should work
