### ISSUE TITLE
Botan fails to build with x86-ldc

### ISSUE THREAD

**Issue by shoo** [etcimon/botan#58]
Build fails in ldc x86 environment. `dub build -a=x86 --compiler=ldc2` (on Windows and Linux both)
https://github.com/shoo/Cookbook/runs/1986323878?check_suite_focus=true#step:5:129
```
 ../../../.dub/packages/botan-15ff68b93eb60a9291c98e066fb1a94af66509d4/botan/source/botan/entropy/rdrand.d(72,23): Error: unknown opcode `rdrand`
```

I saw @etcimon discussing this in the ldc development project:
https://github.com/ldc-developers/ldc/issues/3299
I'm interested in the results.

In addition to this, there are other errors in https://github.com/etcimon/botan/blob/15ff68b93eb60a9291c98e066fb1a94af66509d4/source/botan/block/serp_x86_32.d#L235
```
source\botan\block\serp_x86_32.d(235,5): Error: Statement not allowed in naked function
```

**Comment by shoo** [comment]
Oops...
The version of Botan used is as follows:
```
dependency "botan"      version="15ff68b93eb60a9291c98e066fb1a94af66509d4" repository="git+https://github.com/etcimon/botan.git"
dependency "botan-math" version="1b85c88260ed381124aa3b20418e46d0fba7a0f6" repository="git+https://github.com/etcimon/botan-math.git"
```

**Comment by etcimon** [comment]
It should work now!
