### ISSUE TITLE
Compilation fails on latest dmd and ldc

### ISSUE THREAD

**Issue by shakor0** [etcimon/botan#61]
DMD: DMD64 D Compiler v2.100.2
LDC: LDC - the LLVM D compiler (1.30.0)

`botan-math 1.0.3: target for configuration "regular" is up to date.
memutils 1.0.4: building configuration "secure"...
../../../.dub/packages/memutils-1.0.4/memutils/source/memutils/rbtree.d(734,2): Deprecation: Usage of the `body` keyword is deprecated. Use `do` instead.
../../../.dub/packages/memutils-1.0.4/memutils/source/memutils/rbtree.d(777,2): Deprecation: Usage of the `body` keyword is deprecated. Use `do` instead.
../../../.dub/packages/memutils-1.0.4/memutils/source/memutils/rbtree.d(806,2): Deprecation: Usage of the `body` keyword is deprecated. Use `do` instead.
../../../.dub/packages/memutils-1.0.4/memutils/source/memutils/allocators.d(18,8): Error: module `std.exception` import `enforceEx` not found, did you mean template `std.exception.enforce(E : Throwable = Exception) if (is(typeof(new E("", string.init, size_t.init)) : Throwable) || is(typeof(new E(string.init, size_t.init)) : Throwable))`?`

**Comment by etcimon** [comment]
Everything should be fixed and tagged now
