### ISSUE TITLE
DataSource from string

### ISSUE THREAD

**Issue by GuilhermeStrice** [etcimon/botan#72]
I want to load a publickey from a string how do i proceed?

**Comment by etcimon** [comment]
You can use the following function:

[`PrivateKey loadKey(DataSource in, RandomNumberGenerator rng, string passphrase = "");`](https://github.com/etcimon/botan/blob/3387ed99833dcb717bd9f6ab0fad9f0de766f491/source/botan/pubkey/pkcs8.d#L166)

**Comment by etcimon** [comment]
This example shows how to use DataSource for a string:

https://github.com/etcimon/botan/blob/3387ed99833dcb717bd9f6ab0fad9f0de766f491/source/botan/pubkey/algo/curve25519.d#L308

**Comment by GuilhermeStrice** [comment]
Just wanted to say, that.... I didn't think of it before.... You can just pass the string and it compiles. Thanks for the functions

Better documentation would be awesome

**Comment by GuilhermeStrice** [comment]
Update: it crashes, i guess its by design. Reverting to your solution, doesn't crash
